---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    linkerd.io/extension: smi
    component: smi-adaptor
  name: smi-adaptor
  {{ include "partials.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/extension: smi
      component: smi-adaptor
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        linkerd.io/extension: smi
        component: smi-adaptor
    spec:
      containers:
      - args:
        - smi-adaptor
        - -cluster-domain={{.Values.clusterDomain}}
        image: {{.Values.adaptor.image.registry}}/{{.Values.adaptor.image.name}}:{{.Values.adaptor.image.tag}}
        imagePullPolicy: {{.Values.adaptor.image.pullPolicy}}
        name: smi-adaptor
        ports:
        - containerPort: 9995
          name: admin-http
      serviceAccountName: smi-adaptor
