{{- if (.Values.installNamespace) -}}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{.Values.namespace}}
  labels:
    linkerd.io/extension: smi
  annotations:
    linkerd.io/inject: enabled
{{ end -}}
