name: Integration tests
on:
  pull_request:
    paths-ignore:
    - '*.md'
    - '**/*.md'
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - main
env:
  GH_ANNOTATION: true
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    name: Build SMI Extension
    timeout-minutes: 30
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo "TAG=$(CI_FORCE_CLEAN=1 bin/root-tag)" >> $GITHUB_ENV

        . bin/_docker.sh
        echo "DOCKER_REGISTRY=cr.l5d.io/linkerd" >> $GITHUB_ENV
        echo "DOCKER_BUILDKIT_CACHE=${{ runner.temp }}/.buildx-cache" >> $GITHUB_ENV
    - name: Cache docker layers
      # actions/cache@v2.0.0
      uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx-smi-${{ env.TAG }}
        restore-keys: |
          ${{ runner.os }}-buildx-smi-
    - name: Build SMI docker images and CLI
      run: |
        docker buildx create --driver docker-container --use
        bin/docker-build
        bin/build-cli-bin
    - name: Create artifact with CLI and image archives
      env:
        ARCHIVES: /home/runner/archives
      run: |
        mkdir -p $ARCHIVES
        docker save "cr.l5d.io/linkerd/smi-adaptor:$TAG" > $ARCHIVES/smi-adaptor.tar
        cp target/cli/linux-amd64/linkerd-smi $ARCHIVES
    - name: Upload artifact
      # actions/upload-artifact@v1
      uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
      with:
        name: build-archives
        path: /home/runner/archives
  integration_tests:
    needs: [docker_build]
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        version: [stable, edge]
    name: Integration tests (${{ matrix.version }})
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Try to load cached Go modules
      # actions/cache@v1.1.2
      uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download image archives
      # actions/download-artifact@v1
      uses: actions/download-artifact@18f0f591fbc635562c815484d73b6e8e3980482e
      with:
        name: build-archives
    - name: Load the SMI extension CLI
      run: |
        mkdir -p $HOME/.linkerd2/bin
        echo "$HOME/.linkerd2/bin" >> $GITHUB_PATH
        mv build-archives/linkerd-smi "$HOME/.linkerd2/bin"
        chmod +x $HOME/.linkerd2/bin/linkerd-smi
    - name: Install the Linkerd CLI
      run : |
        if [ '${{ matrix.version }}' == 'edge' ]; then
          curl -sL https://run.linkerd.io/install-edge | sh
        else
          curl -sL https://run.linkerd.io/install | sh
        fi
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0
    - name: Run Integration Tests
      run: |
        GO111MODULE=on go test --failfast --mod=readonly "./test" --linkerd="$HOME/.linkerd2/bin/linkerd" --integration-tests
