name: Unit tests
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - main
jobs:
  go_unit_tests:
    name: Go unit tests
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    container:
      image: golang:1.19
    steps:
    - name: Checkout code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - name: Go unit tests
      run: |
        go install gotest.tools/gotestsum@v0.4.2
        gotestsum -- -cover -race -v -mod=readonly ./...
